apiVersion: v1
kind: Namespace
metadata:
  name: asodemo
---
apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: yungez-asodemo-rg
  namespace: asodemo
spec:
  location: eastus
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServer
metadata:
  name: postgres0902
  namespace: asodemo
spec:
  location: eastus
  owner:
    name: yungez-asodemo-rg
  version: "13"
  sku:
    name: Standard_D2ds_v4
    tier: GeneralPurpose
  administratorLogin: azureuser
  administratorLoginPassword:
    name: postgres-secret
    key: PASSWORD
  storage:
    storageSizeGB: 128
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersDatabase
metadata:
  name: votedb
  namespace: asodemo
spec:
  owner:
    name: postgres0902
  charset: utf8
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersFirewallRule
metadata:
  name: asodemo-allow-all
  namespace: asodemo
spec:
  owner:
    name: postgres0902
  # The following address range allows anybody to connect to this server.
  # This should only be used for demo purposes and not in production!
  # There are other ways to control server access which are not covered here, you can see more about it here:
  # https://docs.microsoft.com/azure/postgresql/flexible-server/concepts-security#network-security
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255

-----------
# get below from envs
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: asodemo
stringData:
  USERNAME: "azureuser"
  PASSWORD: "myfakepassword"
  SERVER:   "postgres0902.postgres.database.azure.com"
  DATABASE: "votedb"
  PORT:     "5432"